stages:
 - build
 - test
 
variables:
 test: "CoreWebAPI.tests"
 
before_script:
 - "cd C:\\Dev\\examples\\WebAPI-NETCORE3\\CoreWebAPI"
 - "dotnet restore"
build:
 stage: build
 script:
  - "dotnet build"

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"